name: "Action Build WordPress Project to Releases"
description: "Action to build a Theme or Plugiin and get the finished result attached to the release assets on GitHub."
author: "Fabian Kägy"
inputs:
  ignore:
    description: "Comma Sepperated list of files to ignore. E.g. 'node_modules, build/index.js'"
    default: ""
  GITHUB_PERSONAL_ACCESS_TOKEN:
    description: "GitHub Personal Access Token to be able to get your files and create the release."
    required: true
runs:
  using: "node12"
  main: "index.js"
